import Head from 'next/head'
import Header from '../components/Header'
import styles from "../styles/Home.module.css"
import Banner from '../components/Banner'
import MyCollection from '../components/MyCollection'
import Transaction from '../components/Transaction'
import Footer from '../components/Footer'
import { setGlobalState } from '../components/GlobalState'
import { useEffect } from 'react'

export default function Home() {

  useEffect(() => {
    window.ethereum.on('accountsChanged', async (accounts) => {
      setGlobalState("connectedAccount", accounts[0])
    })
  }, [])

  return (
    <>
      <Head>
        <title>Solanart 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Header/>
        <Banner />
        <MyCollection />
        <Transaction />
        <Footer />
      </main>
    </>
  )
}

